INSERT INTO roles (name) VALUES ('USER') ON DUPLICATE KEY UPDATE name=name;
INSERT INTO roles (name) VALUES ('ADMIN') ON DUPLICATE KEY UPDATE name=name;
INSERT INTO roles (name) VALUES ('EDITOR') ON DUPLICATE KEY UPDATE name=name;
