ALTER TABLE comments MODIFY COLUMN content TINYTEXT;
ALTER TABLE news MODIFY COLUMN content TINYTEXT;
ALTER TABLE news_approval MODIFY COLUMN comment LONGTEXT;
ALTER TABLE notifications MODIFY COLUMN message TINYTEXT;